import { GDSCEvent } from "@/types/gdsc-event";

export const testEvents: GDSCEvent[] = [
  {
    id: "66bf19a78e5a5cdea29e9dda",
    name: "Tech Conference 2024",
    room: "Hall A",
    location: "New York, NY",
    date: new Date("2024-09-12T09:00:00Z"),
    githubRepo: "https://github.com/techconf2024",
    slidesURL: "https://example.com/slides/techconf2024",
    imageSrc: "https://example.com/images/techconf2024.jpg",
    extraImageSrcs: [],
    description: "A conference bringing together the latest in tech.",
    about:
      "Join industry leaders and tech enthusiasts for a day of networking and learning.",
    attendeeIds: [101, 102, 103],
    organizerIds: [1, 2],
    tags: ["technology", "conference", "networking"],
    type: "virtual",
    duration: 240,
  },
  {
    id: "66bf19a78e5a5cdea29e9dda",
    name: "Tech Conference 2024",
    room: "Hall A",
    location: "New York, NY",
    date: new Date("2024-09-12T09:00:00Z"),
    githubRepo: "https://github.com/techconf2024",
    slidesURL: "https://example.com/slides/techconf2024",
    imageSrc: "https://example.com/images/techconf2024.jpg",
    extraImageSrcs: [
      "https://example.com/images/techconf2024_1.jpg",
      "https://example.com/images/techconf2024_2.jpg",
    ],
    description: "A conference bringing together the latest in tech.",
    about:
      "Join industry leaders and tech enthusiasts for a day of networking and learning.",
    attendeeIds: [101, 102, 103],
    organizerIds: [1, 2],
    tags: ["technology", "conference", "networking"],
    type: "workshop",
    duration: 140,
  },
  {
    id: "43242fsnjasdfjn324",
    name: "AI Workshop",
    room: "Room 202",
    location: "San Francisco, CA",
    date: new Date("2024-10-05T13:00:00Z"),
    githubRepo: "https://github.com/aiworkshop",
    slidesURL: "https://example.com/slides/aiworkshop",
    imageSrc: "https://example.com/images/aiworkshop.jpg",
    extraImageSrcs: [],
    description: "A hands-on workshop focusing on AI technologies.",
    about:
      "Learn the basics of AI and machine learning in this interactive workshop.",
    attendeeIds: [201, 202],
    organizerIds: [3],
    tags: ["AI", "workshop", "technology"],
    type: "competition",
    duration: 30,
  },
  {
    id: "G3242fsnj3452sdfjn324",
    name: "Virtual Coding Bootcamp",
    room: "",
    location: "virtual",
    date: new Date("2024-11-20T00:00:00Z"),
    githubRepo: "https://github.com/virtualbootcamp",
    slidesURL: "https://example.com/slides/virtualbootcamp",
    imageSrc: "https://example.com/images/virtualbootcamp.jpg",
    extraImageSrcs: ["https://example.com/images/virtualbootcamp_1.jpg"],
    description: "An intensive coding bootcamp conducted virtual.",
    about:
      "Develop your coding skills with our comprehensive virtual bootcamp.",
    attendeeIds: [301, 302, 303],
    organizerIds: [4],
    tags: ["coding", "bootcamp", "virtual"],
    type: "virtual",
    duration: 40,
  },
  {
    id: "96bfa5a5cdea29e9dda",
    name: "Data Science Summit",
    room: "Room 305",
    location: "Austin, TX",
    date: new Date("2024-12-01T10:00:00Z"),
    githubRepo: "https://github.com/datasciencesummit",
    slidesURL: "https://example.com/slides/datasciencesummit",
    imageSrc: "https://example.com/images/datasciencesummit.jpg",
    extraImageSrcs: [],
    description: "A summit focusing on the latest trends in data science.",
    about:
      "Explore new data science methodologies and network with professionals.",
    attendeeIds: [401, 402],
    organizerIds: [5, 6],
    tags: ["data science", "summit", "analytics"],
    type: "workshop",
    duration: 20,
  },
  {
    id: "596bf19a78e234529e9dda",
    name: "Web Development Meetup",
    room: "Main Hall",
    location: "Los Angeles, CA",
    date: new Date("2024-08-30T18:00:00Z"),
    githubRepo: "https://github.com/webdevmeetup",
    slidesURL: "https://example.com/slides/webdevmeetup",
    imageSrc: "https://example.com/images/webdevmeetup.jpg",
    extraImageSrcs: ["https://example.com/images/webdevmeetup_1.jpg"],
    description: "Meet other web developers and discuss the latest trends.",
    about: "Network and share knowledge with fellow web developers.",
    attendeeIds: [501, 502, 503],
    organizerIds: [7],
    tags: ["web development", "meetup", "networking"],
    type: "workshop",
    duration: 30,
  },
  {
    id: "asmkdfakmf212345",
    name: "Cybersecurity Workshop",
    room: "Room 109",
    location: "Chicago, IL",
    date: new Date("2024-09-25T11:00:00Z"),
    githubRepo: "https://github.com/cybersecurityworkshop",
    slidesURL: "https://example.com/slides/cybersecurityworkshop",
    imageSrc: "https://example.com/images/cybersecurityworkshop.jpg",
    extraImageSrcs: [],
    description: "A workshop covering key cybersecurity practices.",
    about: "Learn how to protect systems and data in this hands-on workshop.",
    attendeeIds: [601, 602],
    organizerIds: [8, 9],
    tags: ["cybersecurity", "workshop", "security"],
    type: "workshop",
    duration: 60,
  },
  {
    id: "324124efmkskK",
    name: "Blockchain Basics",
    room: "Virtual Room",
    location: "virtual",
    date: new Date("2024-10-15T15:00:00Z"),
    githubRepo: "https://github.com/blockchainbasics",
    slidesURL: "https://example.com/slides/blockchainbasics",
    imageSrc: "https://example.com/images/blockchainbasics.jpg",
    extraImageSrcs: [],
    description: "An introductory course on blockchain technology.",
    about:
      "Understand the fundamentals of blockchain through this virtual course.",
    attendeeIds: [701, 702],
    organizerIds: [10],
    tags: ["blockchain", "course", "virtual"],
    type: "virtual",
    duration: 60,
  },
  {
    id: "23942mkmweral0",
    name: "AI for Healthcare",
    room: "Conference Room 2",
    location: "Seattle, WA",
    date: new Date("2024-11-10T14:00:00Z"),
    githubRepo: "https://github.com/aiforhealthcare",
    slidesURL: "https://example.com/slides/aiforhealthcare",
    imageSrc: "https://example.com/images/aiforhealthcare.jpg",
    extraImageSrcs: ["https://example.com/images/aiforhealthcare_1.jpg"],
    description: "Exploring AI applications in healthcare.",
    about: "Discover how AI is transforming the healthcare industry.",
    attendeeIds: [801, 802],
    organizerIds: [11],
    tags: ["AI", "healthcare", "conference"],
    type: "workshop",
    duration: 70,
  },
  {
    id: "3423k2mksdfsefse",
    name: "DevOps Training",
    room: "Room 310",
    location: "Boston, MA",
    date: new Date("2024-12-15T09:00:00Z"),
    githubRepo: "https://github.com/devopstraining",
    slidesURL: "https://example.com/slides/devopstraining",
    imageSrc: "https://example.com/images/devopstraining.jpg",
    extraImageSrcs: [],
    description: "Training session on DevOps practices and tools.",
    about: "Enhance your DevOps skills with this practical training.",
    attendeeIds: [901, 902],
    organizerIds: [12, 13],
    tags: ["DevOps", "training", "technology"],
    type: "workshop",
    duration: 100,
  },
  {
    id: "23423432ekma",
    name: "Introduction to JavaScript",
    room: "",
    location: "virtual",
    date: new Date("2024-08-25T12:00:00Z"),
    githubRepo: "https://github.com/introtosjs",
    slidesURL: "https://example.com/slides/introtosjs",
    imageSrc: "https://example.com/images/introtosjs.jpg",
    extraImageSrcs: ["https://example.com/images/introtosjs_1.jpg"],
    description: "An virtual course for beginners to JavaScript.",
    about: "Get started with JavaScript programming in this virtual course.",
    attendeeIds: [1001, 1002],
    organizerIds: [14],
    tags: ["JavaScript", "course", "virtual"],
    type: "virtual",
    duration: 120,
  },
  {
    id: "234k2m342dadae",
    name: "Web Development Bootcamp",
    room: "Room 201",
    location: "San Francisco, CA",
    date: new Date("2024-09-20T14:00:00Z"),
    githubRepo: "https://github.com/webdevbootcamp",
    slidesURL: "https://example.com/slides/webdevbootcamp",
    imageSrc: "https://example.com/images/webdevbootcamp.jpg",
    extraImageSrcs: [],
    description: "A full-stack web development bootcamp.",
    about: "Learn the latest web development technologies and frameworks.",
    attendeeIds: [1101, 1102],
    organizerIds: [15],
    tags: ["web development", "bootcamp", "technology"],
    type: "workshop",
    duration: 30,
  },
] as const;
