import { GDSCEvent } from "@/types/gdsc-event";

export const testEvents: GDSCEvent[] = [
  {
    id: "event-001",
    name: "Intro to Web Development",
    room: "Science Hall 242",
    tags: ["web", "development", "beginner"],
    startTime: "10:00 AM",
    endTime: "11:00 AM",
    type: "workshop",
    location: "CSUSM Science Hall",
    date: new Date("2024-09-01T10:00:00"),
    githubRepo: "https://github.com/gdsc-web-intro",
    slidesURL: "https://slides.com/gdsc/web-intro",
    imageSrc: null,
    extraImageSrcs: null,
    description: "An introductory workshop to web development.",
    about: "This workshop is designed for beginners.",
    attendeeIds: ["attendee-101", "attendee-102"],
    organizerIds: ["organizer-001", "organizer-002"],
    usersAttendedIds: ["attendee-101"],
    createdAt: new Date("2024-08-20T08:00:00"),
    updatedAt: new Date("2024-08-21T08:00:00"),
  },
  {
    id: "event-002",
    name: "AI & Machine Learning Challenge",
    room: "Science Hall 242",
    tags: ["AI", "machine learning", "challenge"],
    startTime: "12:00 AM",
    endTime: "1:00 AM",
    type: "challenge",
    location: "CSUSM Tech Center",
    date: new Date("2024-10-15T09:00:00"),
    githubRepo: "https://github.com/gdsc-ai-challenge",
    slidesURL: "https://slides.com/gdsc/ai-challenge",
    imageSrc: null,
    extraImageSrcs: null,
    description: "Compete in AI & Machine Learning tasks.",
    about: "A challenge for AI enthusiasts.",
    attendeeIds: ["attendee-201", "attendee-202", "attendee-203"],
    organizerIds: ["organizer-003", "organizer-004"],
    usersAttendedIds: ["attendee-201", "attendee-202"],
    createdAt: new Date("2024-08-22T08:00:00"),
    updatedAt: new Date("2024-08-23T08:00:00"),
  },
  {
    id: "event-003",
    name: "Hackathon 2024",
    room: "Science Hall 242",
    tags: ["hackathon", "coding", "competition"],
    startTime: "9:00 AM",
    endTime: "11:00 AM",
    type: "competition",
    location: "CSUSM Innovation Hub",
    date: new Date("2024-11-05T08:00:00"),
    githubRepo: "https://github.com/gdsc-hackathon",
    slidesURL: "https://slides.com/gdsc/hackathon",
    imageSrc: null,
    extraImageSrcs: null,
    description: "Join us for a 24-hour hackathon.",
    about: "Build innovative solutions in 24 hours.",
    attendeeIds: [
      "attendee-301",
      "attendee-302",
      "attendee-303",
      "attendee-304",
    ],
    organizerIds: ["organizer-005", "organizer-006"],
    usersAttendedIds: ["attendee-301", "attendee-302"],
    createdAt: new Date("2024-08-24T08:00:00"),
    updatedAt: new Date("2024-08-25T08:00:00"),
  },
] as const;
