import { GDSCUser } from "@/types/gdsc-user";

export const testUsers: GDSCUser[] = [
  {
    id: "user1",
    fullName: "Alice Johnson",
    firstName: "Alice",
    lastName: "Johnson",
    email: "alice.johnson@example.com",
    image: "https://example.com/images/alice.jpg",
    total_points: 150,
    isAdmin: false,
    role: "USER",
    position: "student",
    branch: "project",
    github: "https://github.com/alicejohnson",
    linkedin: "https://linkedin.com/in/alicejohnson",
    instagram: "https://instagram.com/alicejohnson",
    twitter: "https://twitter.com/alicejohnson",
    bio: "Passionate student and aspiring software engineer.",
    tags: ["student", "software engineer"],
  },
  {
    id: "user2",
    fullName: "Bob Smith",
    firstName: "Bob",
    lastName: "Smith",
    email: "bob.smith@example.com",
    total_points: 120,
    isAdmin: true,
    role: "ADMIN",
    position: "president",
    branch: "marketing",
    github: "https://github.com/bobsmith",
    linkedin: "https://linkedin.com/in/bobsmith",
    bio: "Marketing expert with a knack for leadership.",
    tags: ["leader", "marketing"],
  },
  {
    id: "user3",
    fullName: "Charlie Brown",
    firstName: "Charlie",
    lastName: "Brown",
    email: "charlie.brown@example.com",
    image: "https://example.com/images/charlie.jpg",
    total_points: 200,
    isAdmin: false,
    role: "USER",
    position: "mentor",
    branch: "interview",
    twitter: "https://twitter.com/charliebrown",
    bio: "Experienced mentor and interview coach.",
    tags: ["mentor", "interview"],
  },
  {
    id: "user4",
    fullName: "Diana Prince",
    firstName: "Diana",
    lastName: "Prince",
    email: "diana.prince@example.com",
    total_points: 180,
    isAdmin: false,
    role: "USER",
    position: "instructor",
    branch: "project",
    linkedin: "https://linkedin.com/in/dianaprince",
    bio: "instructor with expertise in project management.",
    tags: ["mentor", "project management"],
  },
  {
    id: "user5",
    fullName: "Eve Davis",
    firstName: "Eve",
    lastName: "Davis",
    email: "eve.davis@example.com",
    image: "https://example.com/images/eve.jpg",
    total_points: 90,
    isAdmin: false,
    role: "USER",
    position: "alumni",
    branch: "marketing",
    github: "https://github.com/evedavis",
    linkedin: "https://linkedin.com/in/evedavis",
    bio: "Alumni with a background in marketing.",
    tags: ["alumni", "marketing"],
  },
  {
    id: "user6",
    fullName: "Frank Castle",
    firstName: "Frank",
    lastName: "Castle",
    email: "frank.castle@example.com",
    total_points: 110,
    isAdmin: false,
    role: "USER",
    position: "instructor",
    branch: "interview",
    instagram: "https://instagram.com/frankcastle",
    bio: "Lead interviewer with a focus on technical roles.",
    tags: ["instructor", "technical roles"],
  },
  {
    id: "user7",
    fullName: "Grace Lee",
    firstName: "Grace",
    lastName: "Lee",
    email: "grace.lee@example.com",
    image: "https://example.com/images/grace.jpg",
    total_points: 220,
    isAdmin: true,
    role: "ADMIN",
    position: "instructor",
    branch: "marketing",
    twitter: "https://twitter.com/gracelee",
    bio: "instructor with a strong background in digital marketing.",
    tags: ["instructor", "digital marketing"],
  },
  {
    id: "user8",
    fullName: "Hank Pym",
    firstName: "Hank",
    lastName: "Pym",
    email: "hank.pym@example.com",
    total_points: 75,
    isAdmin: false,
    role: "USER",
    position: "instructor",
    branch: "other",
    linkedin: "https://linkedin.com/in/hankpym",
    bio: "instructor specializing in computer science.",
    tags: ["instructor", "computer science"],
  },
  {
    id: "user9",
    fullName: "Ivy Green",
    firstName: "Ivy",
    lastName: "Green",
    email: "ivy.green@example.com",
    total_points: 130,
    isAdmin: false,
    role: "USER",
    position: "student",
    branch: "project",
    github: "https://github.com/ivygreen",
    bio: "Student with a passion for software development.",
    tags: ["student", "software development"],
  },
  {
    id: "user10",
    fullName: "Jack Black",
    firstName: "Jack",
    lastName: "Black",
    email: "jack.black@example.com",
    image: "https://example.com/images/jack.jpg",
    total_points: 145,
    isAdmin: false,
    role: "USER",
    position: "mentor",
    branch: "project",
    linkedin: "https://linkedin.com/in/jackblack",
    bio: "mentor with extensive experience in project execution.",
    tags: ["mentor", "project execution"],
  },
  {
    id: "user11",
    fullName: "Kara Zor-El",
    firstName: "Kara",
    lastName: "Zor-El",
    email: "kara.zor-el@example.com",
    total_points: 95,
    isAdmin: false,
    role: "USER",
    position: "student",
    branch: "interview",
    twitter: "https://twitter.com/karazor-el",
    bio: "Student interested in interviews and career development.",
    tags: ["student", "career development"],
  },
  {
    id: "user12",
    fullName: "Louis Lane",
    firstName: "Louis",
    lastName: "Lane",
    email: "louis.lane@example.com",
    total_points: 160,
    isAdmin: false,
    role: "USER",
    position: "mentor",
    branch: "marketing",
    github: "https://github.com/louislane",
    linkedin: "https://linkedin.com/in/louislane",
    bio: "Mentor with expertise in marketing strategies.",
    tags: ["mentor", "marketing"],
  },
  {
    id: "user13",
    fullName: "Mia Wong",
    firstName: "Mia",
    lastName: "Wong",
    email: "mia.wong@example.com",
    total_points: 110,
    isAdmin: false,
    role: "USER",
    position: "alumni",
    branch: "other",
    instagram: "https://instagram.com/miawong",
    bio: "Alumni with experience in various tech roles.",
    tags: ["alumni", "tech roles"],
  },
  {
    id: "user14",
    fullName: "Nina Simone",
    firstName: "Nina",
    lastName: "Simone",
    email: "nina.simone@example.com",
    total_points: 85,
    isAdmin: false,
    role: "USER",
    position: "instructor",
    branch: "marketing",
    linkedin: "https://linkedin.com/in/ninasimone",
    bio: "instructor with a focus on digital campaigns.",
    tags: ["instructor", "digital campaigns"],
  },
  {
    id: "user15",
    fullName: "Oscar Isaac",
    firstName: "Oscar",
    lastName: "Isaac",
    email: "oscar.isaac@example.com",
    total_points: 175,
    isAdmin: false,
    role: "USER",
    position: "president",
    branch: "project",
    github: "https://github.com/oscarisaac",
    bio: "President with a strong background in project management.",
    tags: ["president", "project management"],
  },
];
