import { GDSCEvent } from "@/types/gdsc-event";

export const testEvents: GDSCEvent[] = [
  {
    id: "event1",
    name: "Introduction to GitHub",
    room: {
      building: "Science Hall",
      room: 101,
      type: "lecture",
      capacity: 50,
    },
    tags: ["GitHub", "Version Control", "Workshop"],
    duration: 120,
    type: "workshop",
    location: "California State University San Marcos",
    date: new Date("2024-09-15T10:00:00"),
    githubRepo: "https://github.com/example/intro-to-github",
    slidesURL: "https://example.com/slides/intro-to-github",
    imageSrc: null,
    extraImageSrcs: null,
    description:
      "A workshop introducing students to GitHub and version control.",
    about:
      "This workshop will cover the basics of GitHub, including repositories, branches, and pull requests.",
    attendeeIds: [1, 2, 3],
    organizerIds: [101, 102],
    usersAttended: ["alice", "bob"],
    createdAt: new Date("2024-08-28T09:00:00"),
    updatedAt: new Date("2024-08-28T10:00:00"),
  },
  {
    id: "event2",
    name: "Hackathon 2024",
    room: {
      building: "Engineering Building",
      room: 202,
      type: "auditorium",
      capacity: 200,
    },
    tags: ["Hackathon", "Competition", "Tech"],
    duration: 1440,
    type: "competition",
    location: "Online",
    date: new Date("2024-10-01T09:00:00"),
    githubRepo: "https://github.com/example/hackathon-2024",
    slidesURL: "https://example.com/slides/hackathon-2024",
    imageSrc: null,
    extraImageSrcs: null,
    description: "A 24-hour hackathon open to all students.",
    about:
      "Participants will work in teams to build innovative solutions to real-world problems.",
    attendeeIds: [4, 5, 6, 7],
    organizerIds: [103, 104],
    usersAttended: ["charlie", "dave"],
    createdAt: new Date("2024-08-28T11:00:00"),
    updatedAt: new Date("2024-08-28T12:00:00"),
  },
  {
    id: "event3",
    name: "AI and Machine Learning",
    room: {
      building: "Tech Building",
      room: 303,
      type: "classroom",
      capacity: 30,
    },
    tags: ["AI", "Machine Learning", "Lecture"],
    duration: 90,
    type: "workshop",
    location: "California State University San Marcos",
    date: new Date("2024-11-05T14:00:00"),
    githubRepo: "https://github.com/example/ai-ml",
    slidesURL: "https://example.com/slides/ai-ml",
    imageSrc: null,
    extraImageSrcs: null,
    description: "An introductory lecture on AI and machine learning concepts.",
    about:
      "This lecture will cover basic concepts of AI and machine learning, with real-world applications.",
    attendeeIds: [8, 9, 10],
    organizerIds: [105, 106],
    usersAttended: ["eve", "frank"],
    createdAt: new Date("2024-08-28T13:00:00"),
    updatedAt: new Date("2024-08-28T14:00:00"),
  },
  {
    id: "event4",
    name: "Data Science Challenge",
    room: {
      building: "Math Building",
      room: 404,
      type: "classroom",
      capacity: 40,
    },
    tags: ["Data Science", "Challenge", "Tech"],
    duration: 180,
    type: "challenge",
    location: "Hybrid",
    date: new Date("2024-12-10T10:00:00"),
    githubRepo: "https://github.com/example/data-science-challenge",
    slidesURL: "https://example.com/slides/data-science-challenge",
    imageSrc: null,
    extraImageSrcs: null,
    description: "A challenge focused on data science problems and solutions.",
    about:
      "Participants will work on data science problems in teams, using tools like Python and R.",
    attendeeIds: [11, 12, 13],
    organizerIds: [107, 108],
    usersAttended: ["grace", "henry"],
    createdAt: new Date("2024-08-28T15:00:00"),
    updatedAt: new Date("2024-08-28T16:00:00"),
  },
  {
    id: "event5",
    name: "Cybersecurity Workshop",
    room: {
      building: "Cyber Hall",
      room: 505,
      type: "lecture",
      capacity: 100,
    },
    tags: ["Cybersecurity", "Workshop", "Tech"],
    duration: 120,
    type: "workshop",
    location: "California State University San Marcos",
    date: new Date("2024-09-25T13:00:00"),
    githubRepo: "https://github.com/example/cybersecurity-workshop",
    slidesURL: "https://example.com/slides/cybersecurity-workshop",
    imageSrc: null,
    extraImageSrcs: null,
    description: "A workshop on the fundamentals of cybersecurity.",
    about:
      "This workshop will cover essential cybersecurity practices and tools.",
    attendeeIds: [14, 15, 16],
    organizerIds: [109, 110],
    usersAttended: ["ivy", "jack"],
    createdAt: new Date("2024-08-28T17:00:00"),
    updatedAt: new Date("2024-08-28T18:00:00"),
  },
] as const;
